name = "Tram"
version = "2024.6.1"

[build]
kind = "App"
lang = "C++20"
arch = "64"

src_files = ["src/"]
include_files = ["include/"]

filename = "$name"
out = "bin/$build"

warning = "Extra"

toolset = "clang"

[build.debug]
defines = ["DEBUG"]
symbols = true


[build.release]
defines = ["NDEBUG"]
symbols = false
optimize = true


[libraries.toml11]
url = "github@ToruNiina/toml11"
branch = "dev"
include_files = "include/"
lang = "C++20"

[libraries.lib-compile]
url = "gitlab@test"
kind = "Shared"
include_files = "include/"
src_files = "src/"
links = ["fmt", "openssl"]
defines = ["TEST"]

[libraries.local]
url = "fmt" # is treated as "system@"

include_files = "include/"